theme: minima
title: My new Blog
author: stu230485
email: e@mail.com
description: > # this means to ignore newlines until "baseurl:"
  At no time up to date :-)

# social links
twitter_username: none # DO NOT include the @ character, or else the build will fail!
github_username:  stu230485 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
